# Generated by Django 5.2.8 on 2025-11-30 15:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('min_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('works_on', models.CharField(choices=[('ORDER_SUBTOTAL', 'Order Subtotal'), ('SHIPPING', 'Shipping Fee'), ('TOTAL', 'Order Total')], default='ORDER_SUBTOTAL', max_length=20)),
                ('is_fixed', models.BooleanField(default=False)),
                ('dis_value', models.DecimalField(decimal_places=2, help_text='Amount in TWD (if fixed) or percentage (if not fixed)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'db_table': 'discount',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IsAffected',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_snapshot_info', models.JSONField(help_text='Snapshot of discount rules at order time')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Applied Global Discount',
                'verbose_name_plural': 'Applied Global Discounts',
                'db_table': 'is_affected',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('discount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='coupon', serialize=False, to='discounts.discount')),
                ('coupon_code', models.CharField(max_length=50, unique=True)),
                ('max_uses_total', models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited uses', null=True)),
                ('max_uses_per_customer', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'db_table': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='GlobalDiscount',
            fields=[
                ('discount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='global_discount', serialize=False, to='discounts.discount')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority discounts are applied first')),
            ],
            options={
                'verbose_name': 'Global Discount',
                'verbose_name_plural': 'Global Discounts',
                'db_table': 'global_discount',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_snapshot_info', models.JSONField(blank=True, help_text='Snapshot of coupon rules at redemption time', null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redemptions', to='users.customer')),
            ],
            options={
                'verbose_name': 'Coupon Redemption',
                'verbose_name_plural': 'Coupon Redemptions',
                'db_table': 'coupon_redemption',
                'ordering': ['-timestamp'],
            },
        ),
    ]
