# Generated by Django 5.2.8 on 2025-11-30 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponredemption',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemption', to='orders.order'),
        ),
        migrations.AddField(
            model_name='isaffected',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_global_discounts', to='orders.order'),
        ),
        migrations.AddField(
            model_name='couponredemption',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='discounts.coupon'),
        ),
        migrations.AddField(
            model_name='isaffected',
            name='global_discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affected_orders', to='discounts.globaldiscount'),
        ),
        migrations.AddConstraint(
            model_name='isaffected',
            constraint=models.UniqueConstraint(fields=('order', 'global_discount'), name='unique_global_discount_per_order'),
        ),
    ]
