# Generated by Django 6.0 on 2025-12-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_stackable',
            field=models.BooleanField(default=True, help_text='Whether this coupon can be used together with global discounts'),
        ),
    ]
