# Generated by Django 5.2.8 on 2025-12-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_type',
            field=models.CharField(choices=[('default', 'Default'), ('avatar1', 'Avatar 1'), ('avatar2', 'Avatar 2'), ('avatar3', 'Avatar 3'), ('avatar4', 'Avatar 4'), ('avatar5', 'Avatar 5'), ('avatar6', 'Avatar 6'), ('avatar7', 'Avatar 7'), ('avatar8', 'Avatar 8'), ('custom', 'Custom Upload')], default='default', max_length=20),
        ),
    ]
