# Generated by Django 5.2.8 on 2025-12-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_image_user_avatar_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_type',
            field=models.CharField(choices=[('default', 'Default'), ('custom', 'Custom Upload')], default='default', max_length=20),
        ),
    ]
