# Generated by Django 5.2.8 on 2025-11-30 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=255)),
                ('visibility_status', models.CharField(choices=[('PRIVATE', 'Private'), ('PENDING', 'Pending Review'), ('PUBLIC', 'Public'), ('REJECTED', 'Rejected')], default='PRIVATE', max_length=20)),
                ('stl_file_path', models.CharField(max_length=500)),
                ('gcode_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('slicing_info', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '3D Model',
                'verbose_name_plural': '3D Models',
                'db_table': 'model',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='printing_models.model')),
            ],
            options={
                'verbose_name': 'Model Image',
                'verbose_name_plural': 'Model Images',
                'db_table': 'model_image',
            },
        ),
        migrations.CreateModel(
            name='ModelReviewLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, choices=[('PRIVATE', 'Private'), ('PENDING', 'Pending Review'), ('PUBLIC', 'Public'), ('REJECTED', 'Rejected')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('PRIVATE', 'Private'), ('PENDING', 'Pending Review'), ('PUBLIC', 'Public'), ('REJECTED', 'Rejected')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='printing_models.model')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_reviews', to='users.employee')),
            ],
            options={
                'verbose_name': 'Model Review Log',
                'verbose_name_plural': 'Model Review Logs',
                'db_table': 'model_review_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
