# Generated by Django 5.2.8 on 2025-12-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelimage',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Model Image', 'verbose_name_plural': 'Model Images'},
        ),
        migrations.AddField(
            model_name='model',
            name='category',
            field=models.CharField(choices=[('Toys', 'Toys & Games'), ('Home', 'Home & Garden'), ('Gadgets', 'Gadgets & Tech'), ('Art', 'Art & Sculptures'), ('Fashion', 'Fashion & Accessories'), ('Tools', 'Tools & Functional'), ('Education', 'Education & Learning'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='model',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the model', null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='model',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured on homepage'),
        ),
        migrations.AddField(
            model_name='model',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in TWD (null = free)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='stl_file',
            field=models.FileField(blank=True, null=True, upload_to='models/stl/'),
        ),
        migrations.AddField(
            model_name='model',
            name='tags',
            field=models.JSONField(blank=True, help_text='List of tags for searching', null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='models/thumbnails/'),
        ),
        migrations.AddField(
            model_name='model',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modelimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='models/images/'),
        ),
        migrations.AddField(
            model_name='modelimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modelimage',
            name='image_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
