# Generated by Django 6.0 on 2025-12-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing_models', '0002_alter_modelimage_options_model_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='slicing_error',
            field=models.TextField(blank=True, help_text='Error message if slicing failed', null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='slicing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Status of automatic slicing process', max_length=20),
        ),
    ]
