# Generated by Django 6.0 on 2025-12-15 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('printing_models', '0002_alter_modelimage_options_model_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='printing_models.model'),
        ),
    ]
