# Generated by Django 5.2.8 on 2025-11-30 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('printing_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='printing_models.model'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='materials.material'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('customer', 'model', 'material'), name='unique_cart_item_per_customer'),
        ),
    ]
