# Generated by Django 5.2.8 on 2025-11-30 15:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('HOME_DELIVERY', 'Home Delivery'), ('CONVENIENCE_STORE', 'Convenience Store'), ('SELF_PICKUP', 'Self Pickup')], default='HOME_DELIVERY', max_length=30)),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping Option',
                'verbose_name_plural': 'Shipping Options',
                'db_table': 'shipping_option',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavedAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address_type', models.CharField(choices=[('HOME_DELIVERY', 'Home Delivery'), ('CONVENIENCE_STORE', 'Convenience Store'), ('SELF_PICKUP', 'Self Pickup')], help_text='Must match a SHIPPING_OPTION.type for compatibility', max_length=30)),
                ('address_details', models.TextField(help_text='Full address details, recipient name, phone number, etc.')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_addresses', to='users.customer')),
            ],
            options={
                'verbose_name': 'Saved Address',
                'verbose_name_plural': 'Saved Addresses',
                'db_table': 'saved_address',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
